version: 2
sources:
  - name: name_of the source
    schema: name_of_the_schema
    quoting:
      database: false
      schema: false
      identifier: false
    loader: stitch
    tables:
      - name: name_of_table1
      - name: name_of_table2